/** Company admin post-invite review (before Stripe checkout). */
export const COMPANY_ADMIN_ONBOARDING = {
	step1Title: "Basic Details",
	step1Subtitle: "Review the details below to proceed with payment.",
	step2TitlePrefix: "",
	corporationSection: "Corporation Info.",
	companySection: "Company Info.",
	labels: {
		parentCorporationLegalName: "Parent Corporation Legal Name",
		ownershipType: "Ownership Type",
		companyLegalName: "Company Legal Name",
		dbaTradeName: "DBA/ Trade Name",
		websiteUrl: "Website URL",
		companyType: "Company Type",
		officeType: "Office Type",
		regionDataResidency: "Region (Data Residency)",
		industry: "Industry",
		companyPhone: "Company Phone No.",
		companyAddress: "Company Address",
	},
	discard: "Discard",
	proceedToPlan: "Proceed to Plan Details",
	step2IntroMonthly:
		"A monthly subscription plan providing ongoing access to the BSPBlueprint platform and its core tools.",
	step2IntroAnnual:
		"An annual subscription plan providing ongoing access to the BSPBlueprint platform and its core tools.",
	trialSection: "Trial Info.",
	planSection: "Plan Info.",
	labelsPlan: {
		zeroTrial: "Zero Trial",
		trialLength: "Trial Length",
		trialStart: "Trial Start Date",
		trialEnd: "Trial End Date",
		autoConvert: "Auto-convert Trial",
		promoCode: "Promo Code",
		planLevel: "Plan Level",
		planPrice: "Plan Price",
		discount: "Discount",
		invoiceAmount: "Invoice Amount",
		billingCurrency: "Billing Currency",
		on: "On",
		off: "Off",
		default: "(Default)",
	},
	paymentNote:
		"Note: Once your payment is complete, you'll be redirected to the company overview for more info.",
	proceedToPayment: "Proceed to Payment",
	proceeding: "Opening checkout…",
	noPlanTitle: "Plan not configured",
	noPlanBody:
		"This company does not have a plan assigned yet. Contact support if you need help.",
	checkoutDisabled:
		"Checkout is not available yet. Ensure a plan with billing is assigned, or contact support.",
	overviewPageTitle: "Company overview",
	overviewPageSubtitle:
		"Your subscription is active. Below is the company profile we have on file.",
	overviewCardTitle: "Basic Details",
	overviewCardSubtitle: "Corporation and company information.",
	subscriptionStatusLabel: "Subscription status:",
	companiesListCardTitle: "Companies",
	multiCompanyTitle: "Your companies",
	multiCompanySubtitle:
		"You are a company admin for the organizations below. Complete payment where required, or open the company profile.",
	backToCompanies: "Back to companies",
	colCompany: "Company",
	colCorporation: "Parent corporation",
	colStatus: "Status",
	colAction: "Action",
	statusActive: "Active",
	statusPaymentDue: "Payment due",
	statusPending: "Pending setup",
	viewCompany: "View company",
} as const;
