/**
 * Do not edit directly, this file was auto-generated.
 */

export const bspGray50 = "#f8f7fb"; // Generated from Tailwind Color System
export const bspGray100 = "#f1f0f7"; // Generated from Tailwind Color System
export const bspGray300 = "#d3cde5"; // Generated from Tailwind Color System
export const bspGray400 = "#bcb0d5"; // Generated from Tailwind Color System
export const bspGray500 = "#a190c2"; // Generated from Tailwind Color System
export const bspGray600 = "#8f76b1"; // Generated from Tailwind Color System
export const bspGray700 = "#7d649d"; // Generated from Tailwind Color System
export const bspGray800 = "#685384"; // Generated from Tailwind Color System
export const bspGray900 = "#57456d"; // Generated from Tailwind Color System
export const bspGray950 = "#372d48"; // Generated from Tailwind Color System
export const bspGrayBase = "#ddd9eb"; // Generated from Tailwind Color System
export const bspAlphaDark50 = "rgba(26, 26, 26, 0.06)"; // Generated from Tailwind Color System
export const bspAlphaDark100 = "rgba(26, 26, 26, 0.09)"; // Generated from Tailwind Color System
export const bspAlphaDark200 = "rgba(26, 26, 26, 0.2)"; // Generated from Tailwind Color System
export const bspAlphaDark300 = "rgba(26, 26, 26, 0.28)"; // Generated from Tailwind Color System
export const bspAlphaDark400 = "rgba(26, 26, 26, 0.36)"; // Generated from Tailwind Color System
export const bspAlphaDark500 = "rgba(26, 26, 26, 0.48)"; // Generated from Tailwind Color System
export const bspAlphaDark600 = "rgba(26, 26, 26, 0.6)"; // Generated from Tailwind Color System
export const bspAlphaDark700 = "rgba(26, 26, 26, 0.7)"; // Generated from Tailwind Color System
export const bspAlphaDark800 = "rgba(26, 26, 26, 0.75)"; // Generated from Tailwind Color System
export const bspAlphaDark900 = "rgba(26, 26, 26, 0.8)"; // Generated from Tailwind Color System
export const bspAlphaDark1000 = "#1a1a1a"; // Generated from Tailwind Color System
export const bspAlphaLight50 = "rgba(255, 255, 255, 0.06)"; // Generated from Tailwind Color System
export const bspAlphaLight100 = "rgba(255, 255, 255, 0.09)"; // Generated from Tailwind Color System
export const bspAlphaLight200 = "rgba(255, 255, 255, 0.2)"; // Generated from Tailwind Color System
export const bspAlphaLight300 = "rgba(255, 255, 255, 0.28)"; // Generated from Tailwind Color System
export const bspAlphaLight400 = "rgba(255, 255, 255, 0.36)"; // Generated from Tailwind Color System
export const bspAlphaLight500 = "rgba(255, 255, 255, 0.48)"; // Generated from Tailwind Color System
export const bspAlphaLight600 = "rgba(255, 255, 255, 0.6)"; // Generated from Tailwind Color System
export const bspAlphaLight700 = "rgba(255, 255, 255, 0.7)"; // Generated from Tailwind Color System
export const bspAlphaLight800 = "rgba(255, 255, 255, 0.75)"; // Generated from Tailwind Color System
export const bspAlphaLight900 = "rgba(255, 255, 255, 0.8)"; // Generated from Tailwind Color System
export const bspAlphaLight1000 = "#ffffff"; // Generated from Tailwind Color System
export const bspYellow50 = "#fbf8eb"; // Generated from Tailwind Color System
export const bspYellow100 = "#f6edcb"; // Generated from Tailwind Color System
export const bspYellow200 = "#eedb9a"; // Generated from Tailwind Color System
export const bspYellow400 = "#daa735"; // Generated from Tailwind Color System
export const bspYellow500 = "#cb9127"; // Generated from Tailwind Color System
export const bspYellow600 = "#af711f"; // Generated from Tailwind Color System
export const bspYellow700 = "#8c521c"; // Generated from Tailwind Color System
export const bspYellow800 = "#75431e"; // Generated from Tailwind Color System
export const bspYellow900 = "#64391f"; // Generated from Tailwind Color System
export const bspYellow950 = "#3a1c0e"; // Generated from Tailwind Color System
export const bspYellowBase = "#e0b84a"; // Generated from Tailwind Color System
export const bspPrimary50 = "#f3f6fc"; // Generated from Tailwind Color System
export const bspPrimary100 = "#e7edf7"; // Generated from Tailwind Color System
export const bspPrimary200 = "#c9d8ee"; // Generated from Tailwind Color System
export const bspPrimary300 = "#99b8e0"; // Generated from Tailwind Color System
export const bspPrimary400 = "#6392cd"; // Generated from Tailwind Color System
export const bspPrimary500 = "#3f74b8"; // Generated from Tailwind Color System
export const bspPrimary700 = "#264a7e"; // Generated from Tailwind Color System
export const bspPrimary800 = "#233f69"; // Generated from Tailwind Color System
export const bspPrimary900 = "#223758"; // Generated from Tailwind Color System
export const bspPrimary950 = "#17233a"; // Generated from Tailwind Color System
export const bspPrimaryBase = "#305fa1"; // Generated from Tailwind Color System
export const bspBlue50 = "#f1f6fd"; // Generated from Tailwind Color System
export const bspBlue100 = "#deebfb"; // Generated from Tailwind Color System
export const bspBlue200 = "#c5ddf8"; // Generated from Tailwind Color System
export const bspBlue300 = "#9dc8f3"; // Generated from Tailwind Color System
export const bspBlue400 = "#6faaeb"; // Generated from Tailwind Color System
export const bspBlue500 = "#4d89e4"; // Generated from Tailwind Color System
export const bspBlue700 = "#2f5ac6"; // Generated from Tailwind Color System
export const bspBlue800 = "#2c4ba1"; // Generated from Tailwind Color System
export const bspBlue900 = "#29417f"; // Generated from Tailwind Color System
export const bspBlue950 = "#1d294e"; // Generated from Tailwind Color System
export const bspBlueBase = "#3a6fd8"; // Generated from Tailwind Color System
export const bspRed50 = "#fdf3f3"; // Generated from Tailwind Color System
export const bspRed100 = "#faeae9"; // Generated from Tailwind Color System
export const bspRed200 = "#f6d5d5"; // Generated from Tailwind Color System
export const bspRed300 = "#eeb3b4"; // Generated from Tailwind Color System
export const bspRed400 = "#e4888b"; // Generated from Tailwind Color System
export const bspRed500 = "#d65d65"; // Generated from Tailwind Color System
export const bspRed700 = "#a12f3f"; // Generated from Tailwind Color System
export const bspRed800 = "#872a3a"; // Generated from Tailwind Color System
export const bspRed900 = "#742737"; // Generated from Tailwind Color System
export const bspRed950 = "#401119"; // Generated from Tailwind Color System
export const bspRedBase = "#c44755"; // Generated from Tailwind Color System
export const bspBWBlack = "#000000"; // Generated from Tailwind Color System
export const bspBWTransparent = "rgba(0, 0, 0, 0)"; // Generated from Tailwind Color System
export const bspBWWhite = "#ffffff"; // Generated from Tailwind Color System
export const bspSecondary50 = "#f2f8f9"; // Generated from Tailwind Color System
export const bspSecondary100 = "#deecef"; // Generated from Tailwind Color System
export const bspSecondary200 = "#c0d9e1"; // Generated from Tailwind Color System
export const bspSecondary300 = "#94bdcc"; // Generated from Tailwind Color System
export const bspSecondary500 = "#467e94"; // Generated from Tailwind Color System
export const bspSecondary600 = "#3d687d"; // Generated from Tailwind Color System
export const bspSecondary700 = "#365668"; // Generated from Tailwind Color System
export const bspSecondary800 = "#334957"; // Generated from Tailwind Color System
export const bspSecondary900 = "#2e3f4b"; // Generated from Tailwind Color System
export const bspSecondary950 = "#1b2831"; // Generated from Tailwind Color System
export const bspSecondaryBase = "#7aa9bb"; // Generated from Tailwind Color System
export const bspGreen50 = "#effaf5"; // Generated from Tailwind Color System
export const bspGreen100 = "#d9f2e4"; // Generated from Tailwind Color System
export const bspGreen200 = "#b6e4cd"; // Generated from Tailwind Color System
export const bspGreen300 = "#86cfaf"; // Generated from Tailwind Color System
export const bspGreen400 = "#54b38c"; // Generated from Tailwind Color System
export const bspGreen600 = "#22795a"; // Generated from Tailwind Color System
export const bspGreen700 = "#1b614a"; // Generated from Tailwind Color System
export const bspGreen800 = "#184d3c"; // Generated from Tailwind Color System
export const bspGreen900 = "#144032"; // Generated from Tailwind Color System
export const bspGreen950 = "#0a241d"; // Generated from Tailwind Color System
export const bspGreenBase = "#2f8f6b"; // Generated from Tailwind Color System
export const bspGunmetalGray50 = "#f2f8f9"; // Generated from Tailwind Color System
export const bspGunmetalGray100 = "#deecef"; // Generated from Tailwind Color System
export const bspGunmetalGray200 = "#c1dbe0"; // Generated from Tailwind Color System
export const bspGunmetalGray300 = "#96c1ca"; // Generated from Tailwind Color System
export const bspGunmetalGray400 = "#649dac"; // Generated from Tailwind Color System
export const bspGunmetalGray500 = "#498291"; // Generated from Tailwind Color System
export const bspGunmetalGray600 = "#3f6b7b"; // Generated from Tailwind Color System
export const bspGunmetalGray700 = "#385966"; // Generated from Tailwind Color System
export const bspGunmetalGray800 = "#344c56"; // Generated from Tailwind Color System
export const bspGunmetalGray900 = "#2f414a"; // Generated from Tailwind Color System
export const bspGunmetalGrayBase = "#1a272e"; // Generated from Tailwind Color System
export const bsp2xsColor = "rgba(0, 0, 0, 0.05)";
export const bsp2xsX = 0;
export const bsp2xsY = 1;
export const bsp2xsBlur = 0;
export const bsp2xsSpread = 0;
export const bspXsColor = "rgba(0, 0, 0, 0.05)";
export const bspXsX = 0;
export const bspXsY = 1;
export const bspXsBlur = 2;
export const bspXsSpread = 0;
export const bspSmColor = "rgba(0, 0, 0, 0.1)";
export const bspSmShadow1X = 0;
export const bspSmShadow1Y = 1;
export const bspSmShadow1Blur = 3;
export const bspSmShadow1Spread = 0;
export const bspSmShadow2X2 = 0;
export const bspSmShadow2Y = 1;
export const bspSmShadow2Blur = 2;
export const bspSmShadow2Spread = -1;
export const bsp2xlColor = "rgba(0, 0, 0, 0.25)";
export const bsp2xlX = 0;
export const bsp2xlY = 25;
export const bsp2xlBlur = 50;
export const bsp2xlSpread = 12;
export const bspMdColor = "rgba(0, 0, 0, 0.1)";
export const bspMdShadow1X = 0;
export const bspMdShadow1Y = 4;
export const bspMdShadow1Blur = 6;
export const bspMdShadow1Spread = -1;
export const bspMdShadow2X = 0;
export const bspMdShadow2Y = 2;
export const bspMdShadow2Spread = -2;
export const bspMdShadow2Blur = 4;
export const bspLgColor = "rgba(0, 0, 0, 0.1)";
export const bspLgShadow1X = 0;
export const bspLgShadow1Y = 10;
export const bspLgShadow1Blur = 15;
export const bspLgShadow1Spread = -3;
export const bspLgShadow2X = 0;
export const bspLgShadow2Y = 4;
export const bspLgShadow2Spread = 6;
export const bspLgShadow2Blur = -4;
export const bspXlColor = "rgba(0, 0, 0, 0.1)";
export const bspXlShadow1X = 0;
export const bspXlShadow1Y = 20;
export const bspXlShadow1Blur = 25;
export const bspXlShadow1Spread = -5;
export const bspXlShadow2X = 0;
export const bspXlShadow2Y = 8;
export const bspXlShadow2Spread = 10;
export const bspXlShadow2Blur = -6;
export const bspFontDefinitionsFontFamilySans = "Inter";
export const bspFontDefinitionsFontFamilySerif = "Inter";
export const bspFontDefinitionsFontFamilyMonospace = "Inter";
export const bspFontDefinitionsFontFamilyHeadings = "Inter";
export const bspFontDefinitionsFontFamilyBody = "Inter";
export const bspHeading1Weight = "Semibold";
export const bspHeading1FontSize = 48;
export const bspHeading1LineHeight = 48;
export const bspHeading1Spacing = 48;
export const bspHeading1LetterSpacing = -1.5;
export const bspHeading2Weight = "Semibold";
export const bspHeading2FontSize = 30;
export const bspHeading2LineHeight = 30;
export const bspHeading2Spacing = 30;
export const bspHeading2LetterSpacing = -1;
export const bspHeading3Weight = "Semibold";
export const bspHeading3FontSize = 24;
export const bspHeading3LineHeight = 28;
export const bspHeading3Spacing = 20;
export const bspHeading3LetterSpacing = -1;
export const bspHeading4Weight = "Semibold";
export const bspHeading4FontSize = 20;
export const bspHeading4LineHeight = 24;
export const bspHeading4Spacing = 20;
export const bspHeading4LetterSpacing = 0;
export const bspParagraphParagraphWeight = "Regular";
export const bspParagraphParagraphBoldWeight = "Semibold";
export const bspParagraphParagraphMediumWeight = "Medium";
export const bspParagraphRegularFontSize = 16;
export const bspParagraphRegularLineHeight = 24;
export const bspParagraphRegularSpacing = 16;
export const bspParagraphRegularLetterSpacing = 0;
export const bspParagraphSmallFontSize = 14;
export const bspParagraphSmallLineHeight = 21;
export const bspParagraphSmallSpacing = 14;
export const bspParagraphSmallLetterSpacing = 0;
export const bspParagraphMiniFontSize = 12;
export const bspParagraphMiniLineHeight = 16;
export const bspParagraphMiniSpacing = 12;
export const bspParagraphMiniLetterSpacing = 0;
export const bspMonospacedFontWeight = "Regular";
export const bspMonospacedFontSize = 16;
export const bspMonospacedLineHeight = 24;
export const bspMonospacedLetterSpacing = 0;
export const bspMonospacedSpacing = 16;
export const bspAbsolute0 = 0;
export const bspAbsolute1 = 4;
export const bspAbsolute2 = 8;
export const bspAbsolute3 = 12;
export const bspAbsolute4 = 16;
export const bspAbsolute5 = 20;
export const bspAbsolute6 = 24;
export const bspAbsolute7 = 28;
export const bspAbsolute8 = 32;
export const bspAbsolute9 = 36;
export const bspAbsolute10 = 40;
export const bspAbsolute11 = 44;
export const bspAbsolute12 = 48;
export const bspAbsolute14 = 56;
export const bspAbsolute16 = 64;
export const bspAbsolute20 = 80;
export const bspAbsolute24 = 96;
export const bspAbsolute28 = 112;
export const bspAbsolute32 = 128;
export const bspAbsolute36 = 144;
export const bspAbsolute40 = 160;
export const bspAbsolute44 = 176;
export const bspAbsolute48 = 192;
export const bspAbsolute52 = 208;
export const bspAbsolute56 = 224;
export const bspAbsolute60 = 240;
export const bspAbsolute64 = 256;
export const bspAbsolute72 = 288;
export const bspAbsolute80 = 320;
export const bspAbsolute96 = 384;
export const bspAbsoluteRadius8 = 8;
export const bspAbsoluteRadius6 = 6;
export const bspAbsoluteRadius12 = 12;
export const bspAbsoluteRadius4 = 4;
export const bspAbsoluteRadius10 = 10;
export const bspAbsoluteRadiusInfinite = 9999;
export const bspAbsoluteRadius2 = 2;
export const bspAbsoluteRadius16 = 16;
export const bspAbsoluteRadius24 = 24;
export const bspAbsoluteRadius32 = 32;
export const bspAbsolute15 = 6;
export const bspAbsolute25 = 10;
export const bspAbsolute35 = 14;
export const bspAbsoluteInfinite = 9999;
export const bspAbsolute05 = 2;
export const bspSemanticRoundedXs = 2;
export const bspSemanticRoundedLg = 8;
export const bspSemanticRoundedXl = 12;
export const bspSemanticRoundedMd = 6;
export const bspSemanticRoundedSm = 4;
export const bspSemanticRoundedFull = 9999;
export const bspSemanticRoundedNone = 0;
export const bspSemanticRounded2xl = 16;
export const bspSemanticRounded3xl = 24;
export const bspSemantic3xs = 2;
export const bspSemantic2xs = 4;
export const bspSemanticXs = 8;
export const bspSemanticMd = 16;
export const bspSemanticLg = 20;
export const bspSemanticXl = 24;
export const bspSemantic2xl = 32;
export const bspSemantic3xl = 40;
export const bspSemantic4xl = 48;
export const bspSemantic5xl = 64;
export const bspTextTextError = "#c44755";
export const bspTextTextLinkHover = "#2f5ac6";
export const bspTextTextLink = "#3a6fd8";
export const bspTextTextDisabled = "#bcb0d5";
export const bspTextTextWarning = "#8c521c";
export const bspTextTextSuccess = "#22795a";
export const bspTextTextTertiary = "#467e94";
export const bspTextTextPlaceholder = "#bcb0d5";
export const bspTextTextSecondary = "#3f6b7b";
export const bspTextTextPrimary = "#2f414a";
export const bspTextTextWhite = "#ffffff";
export const bspBorderBorderSuccess = "#2f8f6b";
export const bspBorderBorderError = "#c44755";
export const bspBorderBorderFocus = "#305fa1";
export const bspBorderBorderDisabled = "#ddd9eb";
export const bspBorderBorderWarning = "#cb9127";
export const bspBorderBorderActive = "#305fa1";
export const bspBorderBorderHover = "#c9d8ee";
export const bspBorderBorderSecondary = "#d3cde5";
export const bspBorderBorderPrimary = "#ddd9eb";
export const bspIconIconInfo = "#3a6fd8";
export const bspIconIconWarning = "#cb9127";
export const bspIconIconBrand = "#305fa1";
export const bspIconIconOnAccent = "#ffffff";
export const bspIconIconTertiary = "#467e94";
export const bspIconIconSuccess = "#2f8f6b";
export const bspIconIconSecondary = "#3f6b7b";
export const bspIconIconDisabled = "#bcb0d5";
export const bspIconIconError = "#c44755";
export const bspIconIconPrimary = "#2f414a";
export const bspFeedbackInfo = "#3a6fd8";
export const bspFeedbackWarningBg = "#fbf8eb";
export const bspFeedbackWarning = "#8c521c";
export const bspFeedbackSuccess = "#2f8f6b";
export const bspFeedbackError = "#c44755";
export const bspFeedbackInfoBg = "#f1f6fd";
export const bspFeedbackSuccessBg = "#effaf5";
export const bspFeedbackErrorBg = "#fdf3f3";
export const bspBgBgTableHeader = "#f8f7fb";
export const bspBgBgPopover = "#ffffff";
export const bspBgBgCardActive = "#f1f0f7";
export const bspBgBgSidebar = "#f8f7fb";
export const bspBgBgCardHover = "#f8f7fb";
export const bspBgBgInverse = "#2f414a";
export const bspBgBgTertiary = "#f8f7fb";
export const bspBgBgCard = "#ffffff";
export const bspBgBgHeader = "#ffffff";
export const bspBgBgTableRowHover = "#f1f0f7";
export const bspBgBgPrimary = "#ffffff";
export const bspBgBgSecondary = "#f1f0f7";
export const bspBgBgModal = "#ffffff";
export const bspBgBgBrandAzureblue = "#305fa1";
export const bspBgBgBrandNordicsea = "#7aa9bb";
export const bspBgBgBrandGreen = "#2f8f6b";
export const bspBgBgBrandYellow = "#e0b84a";
export const bspBgBgBrandRed = "#c44755";
export const bspBgBgBrandBlue = "#3a6fd8";
export const bspBgBgBrandMistygray = "#ddd9eb";
export const bspBgBgBrandGunmetalgray = "#1a272e";
